// Generated by Bison
#include "parser.tab.h"
/*A simple (a.k.a. incomplete) JSON validator.Made as an example to show how to use flex and bison.*/
int main() {
	while(1){
		yyparse();
	}
}

	/*WORD NEWLINE	{ printf("%s",$1); return 1;};*/